### ISSUE TITLE
Error running the Ansible playbook

### ISSUE THREAD

**Issue by david-streamlio** [openmessaging/openmessaging.github.io#15]
I get the following error when I run the Ansible playbook, i.e. ansible-playbook --user ec2-user --inventory `which terraform-inventory` deploy.yaml. 

TASK [template] *********************************************************************************************************************************************
fatal: [52.32.197.2]: FAILED! => {"changed": false, "msg": "Could not find or access 'templates/workers.yaml'\nSearched in:\n\t/Users/david/clone-zone/streamlio/openmessaging-benchmark/driver-kafka/deploy/templates/workers.yaml\n\t/Users/david/clone-zone/streamlio/openmessaging-benchmark/driver-kafka/deploy/templates/workers.yaml"}
fatal: [34.210.26.26]: FAILED! => {"changed": false, "msg": "Could not find or access 'templates/workers.yaml'\nSearched in:\n\t/Users/david/clone-zone/streamlio/openmessaging-benchmark/driver-kafka/deploy/templates/workers.yaml\n\t/Users/david/clone-zone/streamlio/openmessaging-benchmark/driver-kafka/deploy/templates/workers.yaml"}
fatal: [35.164.34.102]: FAILED! => {"changed": false, "msg": "Could not find or access 'templates/workers.yaml'\nSearched in:\n\t/Users/david/clone-zone/streamlio/openmessaging-benchmark/driver-kafka/deploy/templates/workers.yaml\n\t/Users/david/clone-zone/streamlio/openmessaging-benchmark/driver-kafka/deploy/templates/workers.yaml"}
fatal: [34.210.25.99]: FAILED! => {"changed": false, "msg": "Could not find or access 'templates/workers.yaml'\nSearched in:\n\t/Users/david/clone-zone/streamlio/openmessaging-benchmark/driver-kafka/deploy/templates/workers.yaml\n\t/Users/david/clone-zone/streamlio/openmessaging-benchmark/driver-kafka/deploy/templates/workers.yaml"}
	to retry, use: --limit @/Users/david/clone-zone/streamlio/openmessaging-benchmark/driver-kafka/deploy/deploy.retry

PLAY RECAP **************************************************************************************************************************************************
34.209.142.215             : ok=16   changed=9    unreachable=0    failed=0   
34.210.25.99               : ok=16   changed=10   unreachable=0    failed=1   
34.210.26.26               : ok=16   changed=10   unreachable=0    failed=1   
34.217.209.153             : ok=16   changed=9    unreachable=0    failed=0   
34.217.46.93               : ok=14   changed=8    unreachable=0    failed=0   
34.217.62.17               : ok=14   changed=8    unreachable=0    failed=0   
35.164.34.102              : ok=16   changed=10   unreachable=0    failed=1   
52.24.111.209              : ok=16   changed=9    unreachable=0    failed=0   
52.32.197.2                : ok=16   changed=10   unreachable=0    failed=1   
54.190.52.166              : ok=14   changed=8    unreachable=0    failed=0

**Comment by sijie** [comment]
This fix at openmessaging/openmessaging-benchmark#35 is merged. @david-streamlio can you try it again?

**Comment by david-streamlio** [comment]
I will do a pull and re-try after the Pulsar test stops running...I am seeing issues with that benchmark as well
