### ISSUE TITLE
How to build the website locally ?

### ISSUE THREAD

**Issue by eolivelli** [openmessaging/openmessaging.github.io#36]
My latest changes seems to be merged
https://github.com/openmessaging/openmessaging.github.io/commit/70008e8e7509c1f2d1f127d1e803da79b92b1342

but the website is not updated.

I am not able to build the website locally, due to some Ruby gem error

**Comment by vongosling** [comment]
have you checked the latest update?

**Comment by eolivelli** [comment]
cool 
thanks
