### ISSUE TITLE
XMPP

### ISSUE THREAD

**Issue by Echolon** [openmessaging/openmessaging.github.io#4]
Hello,

Why doesn't the Foundation focus on existing standards like XMPP and starts to improve those?

How many systems do we wanna add until it works?

**Comment by vongosling** [comment]
@Echolon XMPP is just a wire-level standard and mainly focus on mobile. We also consider this area in OpenMessaging. BTW, this is not a right place to discuss problem here. Could you put your question at here https://github.com/openmessaging/specification
