### ISSUE TITLE
SSL cert issue

### ISSUE THREAD

**Issue by caniszczyk** [openmessaging/openmessaging.github.io#40]
http://openmessaging.cloud

<img width="362" alt="Screen Shot 2021-12-01 at 7 43 26 PM" src="https://user-images.githubusercontent.com/63777/144342205-e33ec599-8f59-4c60-a282-429268223544.png">

This should be an easy fix as it's easy to use Lets Encrypt with GitHub pages.

**Comment by vongosling** [comment]
@caniszczyk Hi Chris, I have requested Michael and Keith to help to finish this update. That's all right ~.

**Comment by vongosling** [comment]
BTW, I have requested Keith to help to introduce OpenChaos to donate CNCF, would you like to help to evaluate its feasibility. https://github.com/openmessaging/openchaos
